version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosec
  settings:
    gosec:
      excludes:
        - G104
    errcheck:
      exclude-functions:
        - (*database/sql.DB).Close
        - (*database/sql.Rows).Close
        - (*database/sql.Tx).Rollback
  exclusions:
    paths:
      - vendor

formatters:
  enable:
    - gofmt